"""
match_utils.py

Works with data from mass, wavelength, and elution analyses to
compute a matching score for each potential product generated by Vitual Flask
predictor software. 

The matching score is used to narrow down the range of products associated with a
given reaction to a final number.

Author: natelgrw
Created: 06/01/2025
Last Edited: 6/01/2025
"""